### ISSUE TITLE
Python 3.3 : TypeError: Type str doesn't support the buffer API

### ISSUE THREAD

**Issue by manquer** [git-big-picture/git-big-picture#14]
Tried compiling using python 3.3 ,

```
Traceback (most recent call last):
  File "/usr/bin/git-big-picture", line 5, in <module>
    pkg_resources.run_script('git-big-picture==1.0.0-dev', 'git-big-picture')
  File "/usr/lib/python3.2/site-packages/pkg_resources.py", line 500, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.2/site-packages/pkg_resources.py", line 1241, in run_script
    exec(compile(open(script_filename).read(), script_filename, 'exec'), namespace, namespace)
  File "/usr/lib/python3.2/site-packages/git_big_picture-1.0.0_dev-py3.2.egg/EGG-INFO/scripts/git-big-picture", line 958, in <module>
    main(opts, args)
  File "/usr/lib/python3.2/site-packages/git_big_picture-1.0.0_dev-py3.2.egg/EGG-INFO/scripts/git-big-picture", line 865, in main
    graph = graph_factory(repo_dir)
  File "/usr/lib/python3.2/site-packages/git_big_picture-1.0.0_dev-py3.2.egg/EGG-INFO/scripts/git-big-picture", line 611, in graph_factory
    (lb, rb, ab), (tags, ctags, nctags) = git.get_mappings()
  File "/usr/lib/python3.2/site-packages/git_big_picture-1.0.0_dev-py3.2.egg/EGG-INFO/scripts/git-big-picture", line 578, in get_mappings
    obj_type = self('git cat-file -t %s' % sha1)[0]
  File "/usr/lib/python3.2/site-packages/git_big_picture-1.0.0_dev-py3.2.egg/EGG-INFO/scripts/git-big-picture", line 511, in __call__
    cwd=self.repo_dir).splitlines()
  File "/usr/lib/python3.2/site-packages/git_big_picture-1.0.0_dev-py3.2.egg/EGG-INFO/scripts/git-big-picture", line 490, in get_command_output
    err = '\n'.join(('> ' + e) for e in err.split('\n'))
```

**Comment by esc** [comment]
Can you check master again now, #24 has been merged
