### ISSUE TITLE
Fails on branch names with a single quote

### ISSUE THREAD

**Issue by skybert** [git-big-picture/git-big-picture#96]
```
$ git-big-picture my-project          
Traceback (most recent call last):
  File "/home/torstein/.local/bin/git-big-picture", line 968, in <module>
    main(opts, args)
  File "/home/torstein/.local/bin/git-big-picture", line 871, in main
    graph = graph_factory(repo_dir)
  File "/home/torstein/.local/bin/git-big-picture", line 614, in graph_factory
    (lb, rb, ab), (tags, ctags, nctags) = git.get_mappings()
  File "/home/torstein/.local/bin/git-big-picture", line 568, in get_mappings
    sha1, tag_sha1, ref_type, name = eval(ref_info)
  File "<string>", line 1
    ['69f9ccf5273fdeac218d026dd6033173074', '',  'commit', 'refs/remotes/origin/bugfix/FOO-13-Apple-isn’t-changed-and-Orange-status-isn't-shown-when-video-or-audio-binary-i']
                                                                                                                                                     ^
SyntaxError: invalid syntax
```

## Versions
```
~ $ head -n 1 $(which git-big-picture)
#!/usr/bin/python3
~ $ /usr/bin/python3 --version        
Python 3.7.3
~ $ git-big-picture --version                 
0.10.1
```

**Comment by hartwork** [comment]
Hi @skybert,

that issue is known, was fixed by pull request #62 and [has security implications](https://cve.mitre.org/cgi-bin/cvename.cgi?name=2021-3028). Please use version 1.0.0 or later with the fix, ideally the latest version 1.1.1 that comes with a man page. What distribution of Linux are you running?

Best, Sebastian

**Comment by skybert** [comment]
hi @hartwork,

thanks for your prompt and excellent reply. I can confirm that upgrading to version `1.1.1` resolves the issue:
```
$ pip3 install git-big-picture --upgrade
..
Successfully installed git-big-picture-1.1.1
```
> What distribution of Linux are you running?

I'm on Debian 10 (buster).

Cheers,

-Torstein

**Comment by hartwork** [comment]
Thanks for the update!
